-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME from ANIMAL_OUTS O 
join ANIMAL_INS I
where O.ANIMAL_ID = I.ANIMAL_ID and I.SEX_UPON_INTAKE LIKE 'intact%'
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' or O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID
